resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/28f22dd93ce55b8af3b7e18a5b74762bd919eea8/snapshot.yaml

packages:
  - wallet-poc

extra-deps:
  - ekg-0.4.0.15
  - ekg-json-0.1.0.6
  - time-units-1.0.0

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 28f22dd93ce55b8af3b7e18a5b74762bd919eea8
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 6b5e0923d30f1d331db6b063be047571fb578f37
    subdirs:
      - binary
      - binary/test
      - crypto
      - crypto/test
      - .

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 867680388509df2e699353ff1d971fc359576e75
    subdirs:
      - ouroboros-network
      - io-sim-classes
      - typed-protocols

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 46b1cb807e2ff1f475890a5474e667e472c60d95

nix:
  shell-file: scripts/nix/stack-shell.nix
