resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/ff5fd5f33849be8a826506c34e5b0278f267f804/snapshot.yaml

packages:
  - wallet-poc

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: ff5fd5f33849be8a826506c34e5b0278f267f804
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-chain
    commit: 4d9eec080374179bf15bf9c4fca09cc7d73e5f53
    subdirs:
      - binary
      - binary/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: caabc545ae45c6b702300f7a2c6fdb54cb876b00
    subdirs:
      - typed-protocols

nix:
  shell-file: scripts/nix/stack-shell.nix
